stages:
  - test
  - package

before_script:
  - cd home_alone
  - flutter pub get
  - flutter clean

after_script:
  - cd ..

test:
  image: registry.gitlab.com/home_alone_hack/app:latest
  stage: test
  script:
    - flutter test test/*
  tags:
    - docker
  

package:android:
  image: registry.gitlab.com/home_alone_hack/app:latest
  dependencies:
    - test
  stage: package
  script:
    - flutter build apk
    - cp build/app/outputs/apk/release/app-release.apk ../home_alone.apk
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - ./home_alone.apk
  tags:
    - docker


package:ios:
  dependencies:
    - test
  stage: package
  script:
    - flutter build ios
    - mv build/ios/iphoneos/Runner.app $PWD/..
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - ./Runner.app
  tags:
    - flutter