image: cirrusci/flutter:stable

stages:
  - test
  - build

before_script:
  - cd home_alone
  - flutter pub get
  - flutter clean

after_script:
  - cd ..

test:
  stage: test
  script:
    - flutter test test/*
  tags:
    - docker

build:android:
  dependencies:
    - test
  stage: build
  script:
    - flutter build apk
    - cp build/app/outputs/apk/release/app-release.apk ../home_alone.apk
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - ./home_alone.apk
  tags:
    - docker


build:ios:
  dependencies:
    - test
  stage: build
  script:
    - flutter build ios
    - mv build/ios/iphoneos/Runner.app ../
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - ./Runner.app
  tags:
    - flutter