stages:
  - test
  - package

before_script:
  - projectPath=$PWD
  - cd home_alone
  - flutter pub get
  - flutter clean

after_script:
  - cd $projectPath

test:
  stage: test
  script:
    - flutter test test/*
  tags:
    - flutter
  

package:android:
  dependencies:
    - test
  stage: package
  script:
    - flutter build apk
    - cp build/app/outputs/apk/release/app-release.apk ../home_alone.apk
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - ./home_alone.apk
  tags:
    - flutter


package:ios:
  dependencies:
    - test
  stage: package
  script:
    - flutter build ios
    - mv build/ios/iphoneos/Runner.app $projectPath
    # Archiving doesn't work since we have no development team selected in project
    #- cd ios
    #- xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Debug archive -archivePath $PWD/build/Runner.xcarchive
    #- xcodebuild -exportArchive -archivePath $PWD/build/Runner.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $PWD/build/Runner.ipa -allowProvisioningUpdates
    #- cp $PWD/build/Runner.ipa $projectPath/home_alone.ipa
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - ./Runner.app
      #- ./home_alone.ipa
  tags:
    - flutter